name: Economy
version: '${project.version}'
main: hydra_ft.aternos.me.economy.Main
api-version: 1.19
commands:
  bal:
    description: Check Balance!
    usage: /<command>
    aliases: bank

  pay:
    description: Pay Someone!
    usage: /<command>
    aliases: send

  shop:
    description: Open Item Shop
    usage: /<command>
